name: Lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
      - name: Install dependencies
        run: npm i -g prettier@>=2.0.0
      - name: Lint files
        run: |
          prettier --check .
          shellcheck script/*
